<?php
    $a=10;
    print($a."<br>");
    $a++;//$a=$a+1=>11
    print($a."<br>");
    $a++;//$a=$a+1=>12
    print($a."<br>");
    $a++;//$a=$a+1=>13
    print($a."<br>");
    $a--;//12
    print($a."<br>");
    $a+=3;//15
    print($a."<br>");
    $a*=3;//45
    print($a."<br>");
    $a/=3;//15
    print($a."<br>");
?>